export const hasQuotePermissions = [
    'Austin Baxter',
    'Shawn Baxter',
    'Cassie Baxter',
    'Lacie Baxter',
    'Leisel Utter',
    'Rob Christensen',
    'Spencer Lambert',
    'Andrea Smith',
    'Dara Larsen',
    'Dianna Barnett',
    'Kelvin Urbina',
    'Hanah Carter',
    'Kiera Whiting',
]
