-- AlterTable
ALTER TABLE "SalesOrderProducts" ADD COLUMN     "counted_2xl" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "counted_3xl" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "counted_4xl" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "counted_lg" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "counted_md" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "counted_sm" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "counted_xl" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "counted_xs" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "printed_2xl" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "printed_3xl" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "printed_4xl" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "printed_lg" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "printed_md" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "printed_sm" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "printed_xl" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "printed_xs" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "received_2xl" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "received_3xl" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "received_4xl" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "received_lg" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "received_md" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "received_sm" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "received_xl" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "received_xs" BOOLEAN NOT NULL DEFAULT false;
